2023-02-21 19:55:13,028 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 19:55:30,584 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 19:56:11,628 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\settings\base.py changed, reloading.
2023-02-21 19:56:12,224 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 19:56:21,673 django.request WARNING  Not Found: /
2023-02-21 19:56:36,711 django.request WARNING  Not Found: /dsadjas
2023-02-21 20:31:43,839 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 20:31:46,212 django.request WARNING  Not Found: /
2023-02-21 20:33:18,240 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\profiles\models.py changed, reloading.
2023-02-21 20:33:19,027 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 20:34:51,656 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\ratings\models.py changed, reloading.
2023-02-21 20:34:52,519 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 20:34:56,999 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\ratings\models.py changed, reloading.
2023-02-21 20:34:57,817 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 20:36:10,113 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\ratings\admin.py changed, reloading.
2023-02-21 20:36:11,013 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 20:56:09,647 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 20:56:24,632 django.request WARNING  Not Found: /
2023-02-21 20:59:03,974 django.request WARNING  Unauthorized: /api/v1/auth/users/
2023-02-21 20:59:50,063 django.request WARNING  Unauthorized: /api/v1/auth/users/
2023-02-21 21:01:54,418 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\settings\development.py changed, reloading.
2023-02-21 21:01:55,807 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 21:01:58,515 django.request WARNING  Unauthorized: /api/v1/auth/users/
2023-02-21 21:02:05,023 django.request ERROR    Internal Server Error: /api/v1/auth/users/
Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\djoser\views.py", line 144, in perform_create
    settings.EMAIL.activation(self.request, context).send(to)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\templated_mail\mail.py", line 78, in send
    super(BaseEmailMessage, self).send(*args, **kwargs)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\mail\message.py", line 255, in get_connection
    self.connection = get_connection(fail_silently=fail_silently)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\mail\__init__.py", line 50, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'djcelery_email'
2023-02-21 21:03:16,385 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\settings\development.py changed, reloading.
2023-02-21 21:03:17,505 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 21:03:22,868 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\settings\development.py changed, reloading.
2023-02-21 21:03:23,878 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 21:03:26,991 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\settings\development.py changed, reloading.
2023-02-21 21:03:28,147 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 21:03:30,070 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\settings\development.py changed, reloading.
2023-02-21 21:03:31,228 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 21:03:34,301 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\settings\development.py changed, reloading.
2023-02-21 21:03:35,481 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 21:03:37,573 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\settings\development.py changed, reloading.
2023-02-21 21:03:38,936 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 21:03:43,832 django.request WARNING  Bad Request: /api/v1/auth/users/
2023-02-21 21:06:09,007 django.request WARNING  Not Found: /activate/Mw/bjzp83-8b3475973c733cd8dfdb243c8cd1b60b
2023-02-21 21:06:09,289 django.request WARNING  Not Found: /favicon.ico
2023-02-21 21:10:41,675 django.request WARNING  Not Found: /password/reset/confirm/Mw/bjzphb-02f7b944ba55c896eb394ce94aeb7d24
2023-02-21 21:12:22,281 django.request WARNING  Bad Request: /api/v1/auth/users/reset_password_confirm/
2023-02-21 21:13:13,010 django.request WARNING  Unauthorized: /api/v1/auth/jwt/create/
2023-02-21 21:30:51,370 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\urls.py changed, reloading.
2023-02-21 21:30:53,406 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 21:31:15,941 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 21:36:16,188 django.request ERROR    Internal Server Error: /api/v1/profile/update/biba
Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\middleware\common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PATCH, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PATCH data. Change your form to point to 127.0.0.1:8000/api/v1/profile/update/biba/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2023-02-21 21:36:30,019 django.request ERROR    Internal Server Error: /api/v1/profile/update/biba
Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\middleware\common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/api/v1/profile/update/biba/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2023-02-21 22:43:16,376 django.request WARNING  Unauthorized: /api/v1/profile/agents/all/
2023-02-21 22:47:59,356 django.request WARNING  Unauthorized: /api/v1/profile/top-agents/all/
2023-02-21 22:55:32,491 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-21 22:56:05,128 django.request WARNING  Not Found: /
2023-02-22 21:09:12,801 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:09:21,087 django.request WARNING  Not Found: /
2023-02-22 21:09:21,510 django.request WARNING  Not Found: /favicon.ico
2023-02-22 21:12:32,366 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:12:33,870 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:12:35,152 django.request ERROR    Internal Server Error: /supersecret/properties/property/add/
Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NumericValueOutOfRange: numeric field overflow
DETAIL:  A field with precision 2, scale 2 must round to an absolute value less than 1.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 1891, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 1751, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 1803, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 1226, in save_model
    obj.save()
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py", line 136, in save
    super(Property, self).save(*args, **kwargs)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.DataError: numeric field overflow
DETAIL:  A field with precision 2, scale 2 must round to an absolute value less than 1.

2023-02-22 21:13:47,195 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:13:48,794 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:14:06,052 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:14:07,477 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:14:09,482 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:14:10,662 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:14:16,149 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:14:17,646 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:14:53,317 django.request ERROR    Internal Server Error: /supersecret/properties/property/add/
Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NumericValueOutOfRange: numeric field overflow
DETAIL:  A field with precision 3, scale 2 must round to an absolute value less than 10^1.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 1891, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 1751, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 1803, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 1226, in save_model
    obj.save()
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py", line 136, in save
    super(Property, self).save(*args, **kwargs)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.DataError: numeric field overflow
DETAIL:  A field with precision 3, scale 2 must round to an absolute value less than 10^1.

2023-02-22 21:15:54,032 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:15:55,839 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:16:03,585 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:16:04,902 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:16:07,077 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:16:08,423 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:16:12,855 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:16:14,095 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:17:26,004 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:20:36,192 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:20:37,890 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:20:39,957 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:20:41,293 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:20:44,568 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:20:45,876 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:28:13,611 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:28:15,237 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:28:19,617 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:28:20,989 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:28:27,688 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:28:29,011 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:28:41,194 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:28:42,499 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:28:44,771 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\models.py changed, reloading.
2023-02-22 21:28:45,976 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:32:14,010 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\urls.py changed, reloading.
2023-02-22 21:32:15,924 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:35:18,305 django.request WARNING  Method Not Allowed: /api/v1/properties/create/
2023-02-22 21:35:28,480 django.request WARNING  Bad Request: /api/v1/properties/create/
2023-02-22 21:36:49,450 django.request WARNING  Bad Request: /api/v1/properties/create/
2023-02-22 21:36:54,967 django.request WARNING  Bad Request: /api/v1/properties/create/
2023-02-22 21:38:00,334 django.request ERROR    Internal Server Error: /api/v1/properties/all/
Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 507, in to_representation
    for field in fields:
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `property_number` is not valid for model `Property`.
2023-02-22 21:38:21,080 django.request ERROR    Internal Server Error: /api/v1/properties/all/
Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 507, in to_representation
    for field in fields:
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `property_number` is not valid for model `Property`.
2023-02-22 21:39:25,805 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\serializers.py changed, reloading.
2023-02-22 21:39:27,627 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:41:02,118 django.request ERROR    Internal Server Error: /api/v1/properties/agents/
Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\auth\models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\views.py", line 68, in get_queryset
    queryset = Property.objects.filter(user=user).order_by("-created_at")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'pkid' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001A055E61490>.
2023-02-22 21:41:14,376 django.request ERROR    Internal Server Error: /api/v1/properties/agents/
Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\auth\models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\properties\views.py", line 68, in get_queryset
    queryset = Property.objects.filter(user=user).order_by("-created_at")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'pkid' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001A056104110>.
2023-02-22 21:43:55,572 django.request WARNING  Method Not Allowed: /api/v1/properties/update/aktau-smth/
2023-02-22 21:44:15,773 django.request ERROR    Internal Server Error: /api/v1/properties/update/aktau-smth
Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\middleware\common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/api/v1/properties/update/aktau-smth/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2023-02-22 21:44:25,515 django.request WARNING  Bad Request: /api/v1/properties/update/aktau-smth/
2023-02-22 21:45:43,360 django.request WARNING  Method Not Allowed: /api/v1/properties/update/aktau-smth/
2023-02-22 21:46:09,902 django.request WARNING  Method Not Allowed: /api/v1/properties/update/part-2-smth/
2023-02-22 21:46:28,626 django.request WARNING  Method Not Allowed: /api/v1/properties/update/part-2-smth/
2023-02-22 21:46:58,218 django.request WARNING  Method Not Allowed: /api/v1/properties/update/part-2-smth/
2023-02-22 21:55:25,686 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:56:57,492 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 21:57:05,245 django.request ERROR    Internal Server Error: /supersecret/properties/property/
Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "properties_property" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "properties_property"
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 1932, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\options.py", line 834, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 123, in __init__
    self.get_results(request)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 279, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\core\paginator.py", line 96, in count
    return c()
           ^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\query.py", line 621, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\query.py", line 559, in get_count
    return obj.get_aggregation(using, ["__count"])["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\query.py", line 544, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "properties_property" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "properties_property"
                                          ^

2023-02-22 22:02:03,464 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:06:37,698 django.request WARNING  Unauthorized: /api/v1/profile/me/
2023-02-22 22:07:18,737 django.request WARNING  Bad Request: /api/v1/properties/create/
2023-02-22 22:39:19,426 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\enquiries\models.py changed, reloading.
2023-02-22 22:39:22,007 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:39:59,364 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\urls.py changed, reloading.
2023-02-22 22:40:01,038 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:40:08,346 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:40:33,716 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:40:42,492 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\enquiries\views.py changed, reloading.
2023-02-22 22:40:43,959 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:40:51,614 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:41:02,578 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\enquiries\views.py changed, reloading.
2023-02-22 22:41:04,040 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:47:12,729 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:51:11,543 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\ratings\models.py changed, reloading.
2023-02-22 22:51:12,993 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:51:18,657 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\ratings\models.py changed, reloading.
2023-02-22 22:51:20,061 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:51:32,921 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\ratings\models.py changed, reloading.
2023-02-22 22:51:34,286 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:51:35,847 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\ratings\models.py changed, reloading.
2023-02-22 22:51:37,187 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:51:53,172 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\ratings\models.py changed, reloading.
2023-02-22 22:51:54,461 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:51:58,097 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\apps\ratings\models.py changed, reloading.
2023-02-22 22:51:59,477 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:52:36,797 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\urls.py changed, reloading.
2023-02-22 22:52:38,198 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 22:52:54,452 django.utils.autoreload INFO     C:\Users\batyr\OneDrive\Документы\GitHub\diplomnii_project_babzh\backend\core\urls.py changed, reloading.
2023-02-22 22:52:56,004 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 17:06:54,610 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 17:35:01,024 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 17:45:28,837 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 23:46:10,880 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 23:59:43,576 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 18:01:03,814 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 18:06:52,195 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 18:08:28,009 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 00:08:37,793 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 00:09:06,674 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 00:09:37,257 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 00:11:06,789 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 18:13:02,634 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 18:15:09,485 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-22 18:25:15,326 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 00:28:06,529 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 00:28:57,835 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 00:29:00,844 django.request WARNING  Not Found: /
2023-02-23 02:21:24,956 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 02:22:59,965 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 02:23:58,570 django.request WARNING  Not Found: /
2023-02-23 02:23:58,888 django.request WARNING  Not Found: /favicon.ico
2023-02-23 02:28:02,192 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 02:28:49,097 django.utils.autoreload INFO     /app/apps/enquiries/urls.py changed, reloading.
2023-02-23 02:28:51,387 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 02:29:46,746 django.utils.autoreload INFO     /app/apps/profiles/urls.py changed, reloading.
2023-02-23 02:29:49,335 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 02:30:50,835 django.utils.autoreload INFO     /app/core/settings/base.py changed, reloading.
2023-02-23 02:31:44,608 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-02-23 02:39:47,731 django.utils.autoreload INFO     Watching for file changes with StatReloader
